#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
bspc config top_padding 10

~/.config/polybar/launch.sh &
feh --bg-scale --randomize ~/Pictures/wallpapers/* &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          10

bspc config focused_border_color "#bb9af7"
bspc config normal_border_color "#24283b"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

